#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sat Apr 12 20:41:52 CST 2025
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.1c.zip
